const Products = [
  // 🔹 Chairs (6 items)
  {
    id: 1,
    name: "Sakarias Armchair",
    description: "A cozy armchair with modern minimalism.",
    price: 180,
    category: "chair",
    image: "/chair-1.png",
    rating: 5,
  },
  {
    id: 2,
    name: "Baltsar Lounge Chair",
    description: "A soft lounge chair for reading and relaxation.",
    price: 240,
    category: "chair",
    image: "/chair-2.png",
    rating: 4,
  },
  {
    id: 3,
    name: "Anjay Dining Chair",
    description: "Stylish dining chair with cushioned seating.",
    price: 130,
    category: "chair",
    image: "/chair-3.png",
    rating: 4,
  },
  {
    id: 4,
    name: "Nyantuy Office Chair",
    description: "Ergonomic office chair with full back support.",
    price: 310,
    category: "chair",
    image: "/chair-4.png",
    rating: 5,
  },
  {
    id: 5,
    name: "Lennart Rocking Chair",
    description: "Classic rocking chair for ultimate relaxation.",
    price: 220,
    category: "chair",
    image: "/chair-1.png",
    rating: 3,
  },
  {
    id: 6,
    name: "Karlstad Accent Chair",
    description: "A modern accent chair for stylish interiors.",
    price: 270,
    category: "chair",
    image: "/chair-2.png",
    rating: 4,
  },

  // 🔹 Beds (6 items)
  {
    id: 7,
    name: "Oslo King Bed",
    description: "Spacious king-sized bed with soft cushioning.",
    price: 950,
    category: "Beds",
    image: "/chair-3.png",
    rating: 5,
  },
  {
    id: 8,
    name: "Helsinki Single Bed",
    description: "Compact single bed for minimal spaces.",
    price: 450,
    category: "Beds",
    image: "/chair-4.png",
    rating: 4,
  },
  {
    id: 9,
    name: "Stockholm Queen Bed",
    description: "Elegant queen bed with wooden frame.",
    price: 780,
    category: "Beds",
    image: "/chair-1.png",
    rating: 5,
  },
  {
    id: 10,
    name: "Malmo Bunk Bed",
    description: "Durable bunk bed for kids' room.",
    price: 620,
    category: "Beds",
    image: "/chair-2.png",
    rating: 3,
  },
  {
    id: 11,
    name: "Copenhagen Storage Bed",
    description: "Bed with under-storage drawers.",
    price: 890,
    category: "Beds",
    image: "/chair-3.png",
    rating: 4,
  },
  {
    id: 12,
    name: "Aarhus Luxury Bed",
    description: "Premium luxury bed with cushioned headboard.",
    price: 1200,
    category: "Beds",
    image: "/chair-4.png",
    rating: 5,
  },

  // 🔹 Sofas (6 items)
  {
    id: 13,
    name: "Bergen Two-Seater Sofa",
    description: "Compact sofa for small living rooms.",
    price: 550,
    category: "sofa",
    image: "/chair-1.png",
    rating: 4,
  },
  {
    id: 14,
    name: "Oslo Sectional Sofa",
    description: "Large sectional sofa for modern interiors.",
    price: 890,
    category: "sofa",
    image: "/chair-2.png",
    rating: 5,
  },
  {
    id: 15,
    name: "Trondheim Sofa Bed",
    description: "Convertible sofa bed for guests.",
    price: 670,
    category: "sofa",
    image: "/chair-3.png",
    rating: 4,
  },
  {
    id: 16,
    name: "Reykjavik Recliner Sofa",
    description: "Reclining sofa for maximum comfort.",
    price: 750,
    category: "sofa",
    image: "/chair-4.png",
    rating: 5,
  },
  {
    id: 17,
    name: "Hamar L-Shaped Sofa",
    description: "Spacious L-shaped sofa with modern design.",
    price: 960,
    category: "sofa",
    image: "/chair-1.png",
    rating: 5,
  },
  {
    id: 18,
    name: "Tromso Classic Sofa",
    description: "Elegant classic-style sofa for family rooms.",
    price: 820,
    category: "sofa",
    image: "/chair-2.png",
    rating: 4,
  },

  // 🔹 Lamps (6 items)
  {
    id: 19,
    name: "Oslo Floor Lamp",
    description: "Tall floor lamp with a modern design.",
    price: 180,
    category: "lamps",
    image: "/chair-3.png",
    rating: 4,
  },
  {
    id: 20,
    name: "Helsinki Table Lamp",
    description: "Compact table lamp for reading.",
    price: 120,
    category: "lamps",
    image: "/chair-4.png",
    rating: 3,
  },
  {
    id: 21,
    name: "Stockholm Pendant Lamp",
    description: "Hanging pendant lamp for dining areas.",
    price: 260,
    category: "lamps",
    image: "/chair-1.png",
    rating: 5,
  },
  {
    id: 22,
    name: "Malmo Desk Lamp",
    description: "Adjustable desk lamp for workspaces.",
    price: 95,
    category: "lamps",
    image: "/chair-2.png",
    rating: 4,
  },
  {
    id: 23,
    name: "Copenhagen Wall Lamp",
    description: "Wall-mounted lamp with minimal design.",
    price: 140,
    category: "lamps",
    image: "/chair-3.png",
    rating: 3,
  },
  {
    id: 24,
    name: "Aarhus Night Lamp",
    description: "Soft-glow night lamp for bedrooms.",
    price: 110,
    category: "lamps",
    image: "/chair-4.png",
    rating: 5,
  },
];

export default Products;
